name: CI with docker
on:
  push:
    branches: ["sample-2"]

env:
  IMAGE-NAME: sample-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      -name: Build Docker image
        run: docker build -t $IMAGE-NAME .

      -name: Docker Login
        run: docker Login -u ${{ secrets.Docker_Username }} -p ${{ secrets.Docker_Password }}

      -name: Tag image
        run: docker tag $IMAGE-NAME ${{ secrets.DockerUsername }}/$IMAGE-NAME:Latest}}

      -name: Push image
        run: docker push ${{ secrets.Docker_Username}}/$IMAGE-NAME:Latest}}
