name: Job Level Environment Variables
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job1 running"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job2 running"

  job3:
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job3 running"


